### ISSUE TITLE
HU#03 - Quitar botones reporte

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#103]
## Descripción

Quitar acción reporte del botón acciones de las tarjetas en las pestañas En proceso, seguimiento y resultado

## Objetivo

Para no acceder al formato de reporte

## Criterios de aceptación

- [ ] Quitar acción reporte del botón acciones de las tarjetas en las pestañas En proceso, seguimiento y resultado

## Nodos

Módulo: Calidad
Sección: Análisis

Pestaña: En proceso
Dialogo de acción: Reporte

Pestaña: Seguimiento
Dialogo de acción: Reporte

Pestaña: Resultados
Dialogo de acción: Reporte

**Comment by gustavo-alarcon** [comment]
@MilagrosPalomino  Ferreyros, ya no usará este reporte. Actualizar, no fue parte del requerimiento.
