### ISSUE TITLE
HU#07 - Actualizar la función de envió de data para los correos

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#109]
## Descripción

Incluir todos los datos adicionales en los correos que se envían a los usuarios de la lista de difusión de los diferentes procesos 

## Objetivo

Los usuarios deben de tener toda la información actualizada 

## Criterios de aceptación

- [ ] Actualizar función de envío de data para los correos con los campos adicionales incluidos en los diálogos análisis y formularios de creación de eventos 

## Nodos

Módulo: Calidad

## Imagen referencial

![correo](https://user-images.githubusercontent.com/49251462/134348708-589bfb70-c0af-4766-92ad-06e6d591e37b.png)

## Actualización de diseño

**Comment by gustavo-alarcon** [comment]
:sparkles: Feature done
