### ISSUE TITLE
Bug - No se muestran datos al descargar la tabla de resultados - Módulo calidad

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#125]
## Descripción

Cuando descargo la tabla de resultados en el formato excel no se muestran los datos solo las cabecera de la tabla.

## Criterios de aceptación

- [x] Corregir función de descarga
- [x] si los filtros están activos en la tabla se descargaran los eventos filtrados

## Imagen referencial

![descarga](https://user-images.githubusercontent.com/49251462/134449258-da96c2d7-2806-4017-a661-4a05886c50b6.png)

**Comment by gustavo-alarcon** [comment]
Bug corregido en versión V7.19.25r
