### ISSUE TITLE
HU#14 - Pestaña Pendientes de aprobación

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#26]
- [x] Pestaña pendientes de aprobación
- [x] Indicador de cantidad de W.O.
- [x] Filtros de búsqueda: Taller, WO MAIN, WO CHILD, CLIENTE
- [x] Los filtros de búsqueda se podrán usar a la vez o en diferentes combinaciones (Filtro cascada)
- [x] Botón de descarga en formato excel
- [x] Tabla resumen
- [x] Paginador de tabla
- [x] Consulta a base de datos para traer la lista de los pptos en estado pendientes de aprobación

- [x] Lógica de reconocimiento de ppto: Cuando se modifique el presupuesto la fila se resaltará de color amarillo

- [x] Lógica de actualización de estado a PPTO modificado

- [x] Botón de acciones: Aprobar Ppto, Modificar Ppto, rechazar ppto e Historial.

- [x] Lógica y diálogos de acciones

- [x] Contador de ppto adicionales en tabla

**Comment by gustavo-alarcon** [comment]
✨ Feature done
