### ISSUE TITLE
HU#02 - Subsección Entrada Diaria

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#5]
- [x] Crear subsección
- [x]  Botón de carga de archivos en formato excel
- [x] Generación de tabla resumen
- [x] Botón y acción de botón "Enviar"
- [x] Carga de archivos a base de datos
- [x] Botones de acción por ítem de tabla: Editar y borrar
- [x] Lógica de acciones: editar y borrar
- [x]  Validador de registros para no duplicar entradas
- [x] Validador de upgrade

**Comment by carlos-dubon-ms** [comment]
Note: The current **duplicate budgets** algorithm only checks if woChild isn't repeated, and if it doesn't have a woChild it checks if woMain doesn't repeat. To achieve this all the budgets are fetched.
