### ISSUE TITLE
HU#08 - Listas de procesos por taller

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#74]
## Descripción

Agregar listas de procesos y talleres en configuraciones

## Objetivo

Tener los datos para las listas desplegables de los campos adicionales de los formularios de eventos internos y externos

## Criterios de aceptación

- [x] Agregar los campos taller e indicar proceso para crear un nuevo taller.
- [x] Crear una lista dependiente para procesos por taller
- [x] Condicional ambos campos son obligatorios. en el campo proceso por lo menos se deberá agregar un ítem a la lista.
- [x] Al hacer click en el botón guardar se agregará el nuevo taller y los procesos vinculados a la tabla.
- [x] Los item agregados a la lista de procesos podrán ser borrados haciendo click en el  tachito.
- [x] Crear una nueva tabla para los talleres y procesos
- [x] Las acciones por item son editar y borrar (Las funciones se integraran en otra HU)

## Nodos

Sección: Configuraciones

## Imagen referencial

![Frame 44](https://user-images.githubusercontent.com/49251462/133041561-c87c928c-3658-4ab9-9551-4454a6670e93.jpg)

## Actualización de diseño

![Frame 73 (2)](https://user-images.githubusercontent.com/49251462/133662825-40f41fb5-a451-4c79-bd5d-439c876c7d42.jpg)

**Comment by gustavo-alarcon** [comment]
Se creo un issue adicional de esta tarea, para los diálogos de editar y borrar. #83
