### ISSUE TITLE
HU#11 - Crear Cloud Function para envío de correo

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ingenieria-dsp#78]
## Descripción

Crear Cloud Function que envie data a URL de Ferreyros

## Objetivo

Notificar a los usuarios cuando se generen nuevos eventos internos/externos y se asignen especialistas.

## Criterios de aceptación

- [x] Crear Cloud Function que envie data a URL de Ferreyros para el envio de correos cuando se genere un evento interno o externo.
- [x] Los correos se enviaran a "POR DEFINIR"

- [x] Crear Cloud Function que envie data a URL de Ferreyros para enviar correo cuando se asigne especialista
- [x] Los correos se enviaran a los usuarios que fueron asignados como especialistas

## Nodos

Sección: Eventos internos
Sección: Eventos externos

Sección: Análisis

- Pestaña:  Registro
- Dialogo de acciones: Asignar especialista

**Comment by gustavo-alarcon** [comment]
:sparkles: Feature done
